archivos:
    path:     /
    defaults: { _controller: "SigFichasocialBundle:Archivo:index" }

archivos_show:
    path:     /{id}/show
    defaults: { _controller: "SigFichasocialBundle:Archivo:show" }

archivos_new:
    path:     /new
    defaults: { _controller: "SigFichasocialBundle:Archivo:new" }

archivos_create:
    path:     /create
    defaults: { _controller: "SigFichasocialBundle:Archivo:create" }
    requirements: { _method: post }

archivos_edit:
    path:     /{id}/edit
    defaults: { _controller: "SigFichasocialBundle:Archivo:edit" }

archivos_update:
    path:     /{id}/update
    defaults: { _controller: "SigFichasocialBundle:Archivo:update" }
    requirements: { _method: post|put }

archivos_delete:
    path:     /{id}/delete
    defaults: { _controller: "SigFichasocialBundle:Archivo:delete" }
    requirements: { _method: post|delete }
