Sig\FichasocialBundle\Entity\Archivo:
    type: entity
    table: Archivo
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        codigo:
            type: string
            length: '100'
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }
