Sig\FichasocialBundle\Entity\Domicilio:
    type: entity
    table: Domicilio
    repositoryClass: Sig\FichasocialBundle\Repository\DomicilioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    indexes:
        name_index:
            columns: [ calle, numero, rol ]
    fields:
        calle:
            type: string
            length: '100'
            nullable: true
        numero:
            type: integer
            length: null
            nullable: true
        poblacion:
            type: string
            length: '100'
            nullable: true
        edificio:
            type: string
            length: '100'
            nullable: true
        departamento:
            type: string
            length: '100'
            nullable: true
        casa:
            type: string
            length: '100'
            nullable: true
        chacra:
            type: string
            length: '100'
            nullable: true
        parcela:
            type: string
            length: '100'
            nullable: true
        paradero:
            type: string
            length: '100'
            nullable: true
        sector:
            type: string
            length: '100'
            nullable: true
        unidad:
            type: integer
            length: null
            nullable: true
        rol:
            type: string
            length: '20'
            nullable: true
        rolId:
            type: integer
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    manyToOne:
        persona:
            targetEntity: Persona
            joinColumn:
                name: persona_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
