Sig\FichasocialBundle\Entity\RutaFichaSocial:
    type: entity
    table: RutaFichaSocial
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    manyToMany:
        solicitudes:
            targetEntity: SolicitudFichaSocial
            inversedBy: rutas
            joinTable:
                name: SolicitudesAsignadas
                joinColumns:
                    ruta:
                        referencedColumnName: id
                inverseJoinColumns:
                    solicitud:
                        referencedColumnName: id
    manyToOne:
        estado:
            targetEntity: EstadoRutaFichaSocial
        encuestador:
            targetEntity: EncuestadorFichaSocial
    lifecycleCallbacks: {  }
