Sig\FichasocialBundle\Entity\Usuario:
    type: entity
    table: fos_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
#    indexes:
#        name_index:
#            columns: [ primer_nombre, segundo_nombre, primer_apellido, segundo_apellido ]
    fields:
        primer_nombre:
            type: string
            length: '100'
            nullable: true
        segundo_nombre:
            type: string
            length: '100'
            nullable: true
        primer_apellido:
            type: string
            length: '100'
            nullable: true
        segundo_apellido:
            type: string
            length: '100'
            nullable: true
        telefono:
            type: string
            length: '100'
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }
